[project]
name = "firefly"
version = "6.0.1"
description = "Desktop client application for Nebula - Open source media asset management and broadcast automation system."
requires-python = ">=3.10,<3.12"

dependencies = [
  "websocket-client >=1.3.1",
  "nxtools ==1.6",
  "pydantic >=1.10.2",
  "PySide6 >=6.4.2"
]

[dependency-groups]
dev = [
  "PyQtEnumConverter >=1.0",
  "ruff >=0.6.9",
  "qtsass >=0.3.2",
  "mypy >=1.19.1",
  "pyinstaller >=5.8.0"
]

[tool.ruff]
fix = true
line-length = 88

[tool.ruff.format]
indent-style = "space"
line-ending = "auto"


[tool.ruff.lint]
select = [
    "E",   # pycodestyle errors
    "W",   # pycodestyle warnings
    "F",   # pyflakes
    "I",   # isort
    "C",   # flake8-comprehensions
    "ISC", # flake8-implicit-str-concat
    "C4",  # flake8-comprehensions
    "UP",  # pyupgrade
]

ignore = [
    "ISC001", # incompatible with formatting
    "E721",  # do not compare types, i'll fix this later :)
    "C901",  # too complex. C'mon - this is a complex project
]


[tool.mypy]
plugins = [
  "pydantic.mypy"
]

check_untyped_defs = true
disallow_any_generics = true
exclude = "tests/|venv/|tool/|test_"
explicit_package_bases = true
no_implicit_reexport = true
strict_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
# follow_imports = "silent"
# strict = true
# disallow_untyped_defs = false

[[tool.mypy.overrides]]
module = [
  "user_agents",
  "tomllib",
  "codenamize",
  "aiocache"
]
ignore_missing_imports = true
