name: Build windows binary

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10
          
      - name: Build exe with pyinstaller
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller poetry
          poetry config virtualenvs.create false
          poetry install --no-interaction --no-ansi
          pyinstaller --clean -y --dist dist --name firefly --icon images/firefly.ico --onefile firefly/__main__.py
          copy -r images dist/images
          copy skin.css dist/skin.css
          chown -R --reference=. dist
                    
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: python_exe
          path: dist

