name: Build windows binary

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Build exe with pyinstaller
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --no-interaction --no-ansi
          make build

      - name: Get the version
        id: get_version
        uses: SebRollen/toml-action@v1.0.1
        with:
          file: 'pyproject.toml'
          field: 'tool.poetry.version'
          
      - name: Create zip
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          directory: dist
          filename: firefly-${{ steps.get_version.outputs.value }}-win.zip

      - uses: ncipollo/release-action@v1
        with:
          artifacts: dist/firefly-${{ steps.get_version.outputs.value }}-win.zip
          tag: v${{ steps.get_version.outputs.value }}
          name: Firefly v${{ steps.get_version.outputs.value }}
          body: Firefly ${{ steps.get_version.outputs.value }}
          allowUpdates: true
          draft: true
          prerelease: false
